### ISSUE TITLE
infinite github.com in know_hosts

### ISSUE THREAD

**Issue by xing0231** [webfactory/ssh-agent#168] opened 2023-03-20 15:51 UTC
https://github.com/webfactory/ssh-agent/blob/ea17a056b908d85ca1f46c275ab91389eb65c9fa/index.js#L30
from line 30 to 32 will keep adding the same key to know_hosts over and over by job running. could you add an option to add this to know_hosts or precheck know_hosts has the existing host alreaday? Or run a ssh-keyscan instead by child_process? Thank you!

**Comment by mpdude** [comment] 2023-03-20 20:15
This is a duplicate of #106, happy to take patches!

**Closed by mpdude** 2023-03-20 20:15 UTC
