### ISSUE TITLE
node12 needs upgraded to node16

### ISSUE THREAD

**Issue by sfullerbeckman** [webfactory/ssh-agent#135] opened 2022-10-14 14:21 UTC
Node12 needs upgraded to node16 within this action. Otherwise, all Github Actions workflows throw a warning message whenever they run. This PR should resolve this issue: #134

**Comment by davereid-pfg** [comment] 2022-10-14 15:20
This is a duplicate of https://github.com/webfactory/ssh-agent/issues/131

**Comment by mpdude** [comment] 2022-10-19 11:52
Fixed in #132.

**Closed by mpdude** 2022-10-19 11:52 UTC
